// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxUWuvSNr6MeJ1Pkgy1gaiHb1yAz1gVnk',
    appId: '1:338365232443:web:b2014689e60a4858d4f31e',
    messagingSenderId: '338365232443',
    projectId: 'appbook-4e349',
    authDomain: 'appbook-4e349.firebaseapp.com',
    storageBucket: 'appbook-4e349.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA55Mv26aN3w0hlDw9UFaFgKx1XASyQ7fc',
    appId: '1:338365232443:android:0e433ac104134eced4f31e',
    messagingSenderId: '338365232443',
    projectId: 'appbook-4e349',
    storageBucket: 'appbook-4e349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMo68Tl05ZNfvydGzDuPRhFXEZaM4KWYM',
    appId: '1:338365232443:ios:d1eba15358171485d4f31e',
    messagingSenderId: '338365232443',
    projectId: 'appbook-4e349',
    storageBucket: 'appbook-4e349.firebasestorage.app',
    iosBundleId: 'com.example.bookcycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMo68Tl05ZNfvydGzDuPRhFXEZaM4KWYM',
    appId: '1:338365232443:ios:d1eba15358171485d4f31e',
    messagingSenderId: '338365232443',
    projectId: 'appbook-4e349',
    storageBucket: 'appbook-4e349.firebasestorage.app',
    iosBundleId: 'com.example.bookcycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxUWuvSNr6MeJ1Pkgy1gaiHb1yAz1gVnk',
    appId: '1:338365232443:web:a5d60c6f2b0c3f81d4f31e',
    messagingSenderId: '338365232443',
    projectId: 'appbook-4e349',
    authDomain: 'appbook-4e349.firebaseapp.com',
    storageBucket: 'appbook-4e349.firebasestorage.app',
  );

}