// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA58MvH-lkVFQqfi5AXmVrhGfN9mfo4pig',
    appId: '1:251093022105:web:4a8fb004b5447c7ab78f08',
    messagingSenderId: '251093022105',
    projectId: 'bookcycle-fee8b',
    authDomain: 'bookcycle-fee8b.firebaseapp.com',
    storageBucket: 'bookcycle-fee8b.firebasestorage.app',
    measurementId: 'G-PM20J21EZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_U7tGM7QQ8NDe-uug1uprOUQ02XBtj10',
    appId: '1:251093022105:android:89c6812f07341af3b78f08',
    messagingSenderId: '251093022105',
    projectId: 'bookcycle-fee8b',
    storageBucket: 'bookcycle-fee8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKceXR7D_DNa3m-WCcXLIdS5SiWoPLkhc',
    appId: '1:251093022105:ios:ed87ca15745f8376b78f08',
    messagingSenderId: '251093022105',
    projectId: 'bookcycle-fee8b',
    storageBucket: 'bookcycle-fee8b.firebasestorage.app',
    iosBundleId: 'com.example.bookcycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKceXR7D_DNa3m-WCcXLIdS5SiWoPLkhc',
    appId: '1:251093022105:ios:ed87ca15745f8376b78f08',
    messagingSenderId: '251093022105',
    projectId: 'bookcycle-fee8b',
    storageBucket: 'bookcycle-fee8b.firebasestorage.app',
    iosBundleId: 'com.example.bookcycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA58MvH-lkVFQqfi5AXmVrhGfN9mfo4pig',
    appId: '1:251093022105:web:9de9c732261eed54b78f08',
    messagingSenderId: '251093022105',
    projectId: 'bookcycle-fee8b',
    authDomain: 'bookcycle-fee8b.firebaseapp.com',
    storageBucket: 'bookcycle-fee8b.firebasestorage.app',
    measurementId: 'G-8FVDKP1HHT',
  );
}
